version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install --save
      - run: npm test
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: npx jest --collectCoverage=true
      - store_artifacts:
          path: coverage
workflows:
  build_test:
    jobs:
      - run_tests